### ISSUE TITLE
NameError: global name 'is_time_journal' is not defined

### ISSUE THREAD

**Issue by adamgibbins** [Tagirijus/ledger-plot#1]
Is this a known issue? Is there anything further I can do to debug? (I don't know Python)

Thanks

```
% python ledger-plot.py
Infotext line 1
Infotext line 2

(1) Lines
(2) Linespoints
(3) Boxes
(4) Boxes + Label
(5) Linespoints (Autozero)
(6) Boxes (Autozero)
(7) Boxes (Autozero) + Label
Style [1]: 

Round output? [yes] 

Count entries? [no]: 

Rate: (y)ear, (m)onth or (n)ormal? [normal]: 

Timespan start [1900/01/01]: 
Timespan end [9999/12/31]: 

Show (t)otal or (r)elative values? [total]: 
Include past values? [yes]: 

(+ " not: NAME1, NAME2, ..." = exclude accounts)
(+ " par: PARAMETERS" = manual parameters)

Accounts: 
Add account: Income:Salary
Traceback (most recent call last):
  File "ledger-plot.py", line 754, in <module>
    plot.chose_style()
  File "ledger-plot.py", line 424, in chose_style
    self.chose_count()
  File "ledger-plot.py", line 463, in chose_count
    self.chose_timespan()
  File "ledger-plot.py", line 544, in chose_timespan
    self.chose_accounts()
  File "ledger-plot.py", line 588, in chose_accounts
    self.accounts.append( self.get_array(ledger_file, user) )
  File "ledger-plot.py", line 186, in get_array
    if is_time_journal:
NameError: global name 'is_time_journal' is not defined
```

**Comment by Tagirijus** [comment]
Hey. I am not sure if it could depend on the version of python, but which version of python are you using? Type "python --version" in the terminal.

At the moment this seems weird to me. The variable is just for recognizing time journals. I added something in the function, which caused the bug. Maybe it solved the problem?

Best,
Manu

Am 28.02.2016 um 19:56 schrieb Adam Gibbins:

**Comment by adamgibbins** [comment]
This is running on Python 2.7.11.  I tried Python 3.5.1 too however get `File "ledger-plot.py", line 35
    print 'No settings file found.'
                                  ^
SyntaxError: Missing parentheses in call to 'print'`

**Comment by Tagirijus** [comment]
Yeah, Python 2 is needed. What about the new commit I've did today? Did it help?

**Comment by adamgibbins** [comment]
Unfortunately not, I continue to get the same error.

```
Traceback (most recent call last):
  File "ledger-plot.py", line 756, in <module>
    plot.chose_style()
  File "ledger-plot.py", line 426, in chose_style
    self.chose_count()
  File "ledger-plot.py", line 465, in chose_count
    self.chose_timespan()
  File "ledger-plot.py", line 546, in chose_timespan
    self.chose_accounts()
  File "ledger-plot.py", line 590, in chose_accounts
    self.accounts.append( self.get_array(ledger_file, user) )
  File "ledger-plot.py", line 188, in get_array
    if is_time_journal:
NameError: global name 'is_time_journal' is not defined
```

**Comment by Tagirijus** [comment]
I pushed another possible fix. Is the problem still there?

**Comment by adamgibbins** [comment]
Yup, that fixes, thanks!

**Comment by Tagirijus** [comment]
Good to hear! (=
